### ISSUE TITLE
Use range as expected

### ISSUE THREAD

**Issue by blokeley** [mikeckennedy/python-switch#1]
list(range(5)) gives 0, 1, 2, 3, 4

Your library should do the same or it will astonish users (in a bad way).

https://en.m.wikipedia.org/wiki/Principle_of_least_astonishment

**Comment by mikeckennedy** [comment]
Hi, yes, I came to the same conclusion last night. Here's the update: https://github.com/mikeckennedy/python-switch/commit/86ef5071008b807a730e284bcc013aec532e5a2a

I do dislike the way it reads:

```python
with switch(value) as s:
    s.case(range(1, 6), lambda: get_set_case("1-to-5"))
    s.case(range(6, 7), lambda: get_set_case("6"))
    s.default(lambda: get_set_case('default'))
```

But totally agree that it's what is right based on how Python works.

Thanks,
Michael

**Comment by rob-smallshire** [comment]
You could provide a closed_range function which builds a regular Python half-open range. Something like:

    def closed_range(a, b):
        return range(a, b+1)

giving:

    with switch(value) as s:
        s.case(closed_range(1, 5), lambda: get_set_case("1-to-5"))
        s.case(closed_range(6, 6), lambda: get_set_case("6"))
        s.default(lambda: get_set_case('default'))

**Comment by mikeckennedy** [comment]
@rob-smallshire that's a good idea. I added it here:

https://github.com/mikeckennedy/python-switch/commit/59bd2b871c5fb9a9e4ef72b142f22f5ecc68908e
